version: '3.7'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_DATABASE=pacotesviagens
      - MYSQL_USER=pacotesviagens
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo
    ports:
      - 3306:3306
    networks:
      - backend
    healthcheck:
      test: "/usr/bin/mysql --user=$MYSQL_USER --password=$MYSQL_PASSWORD --execute \"SHOW DATABASES;\""
      interval: 1s
      retries: 120
    restart: always

  mongo:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=pacotesviagens
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo
    ports:
      - 27017:27017
    networks:
      - backend
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 1s
      retries: 120
    restart: always

  web:
    container_name: cursos_web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
       mysql:
          condition: service_healthy
       mongo:
         condition: service_healthy
    networks:
      - backend

networks:
  backend: